-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 10:55:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mylibrarydb
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `mylibrarydb` DEFAULT CHARACTER SET utf8 ;
USE `mylibrarydb` ;


-- -----------------------------------------------------
-- Table `mylibrarydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylibrarydb`.`book` (
  `idbook` INT NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idbook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylibrarydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylibrarydb`.`customer` (
  `idcustomer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylibrarydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylibrarydb`.`transaction` (
  `idtransaction` INT NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  `date` DATE NOT NULL,
  `book_idbook` INT NOT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `fk_transaction_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  INDEX `fk_transaction_book1_idx` (`book_idbook` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mylibrarydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_book1`
    FOREIGN KEY (`book_idbook`)
    REFERENCES `mylibrarydb`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
